version: "3.8"
services:
  nextjs:
    build: ./
  nginx:
    build: ./nginx
    ports:
      - 8080:80
  cloudflared:
    image: "cloudflare/cloudflared:latest"
    container_name: cloudflare-tunnel
    restart: unless-stopped
    command:
      - tunnel
      - --no-autoupdate
      - run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
